# Generated by Django 3.1.1 on 2020-09-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('prioridad', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=3)),
                ('autor', models.CharField(max_length=60)),
                ('tipo_usuario', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=3)),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
