# Generated by Django 3.1.1 on 2020-09-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_anuncio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('prioridad', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=3)),
                ('categoria', models.CharField(max_length=150)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Imagen')),
                ('autor', models.CharField(max_length=60)),
                ('tipo_usuario', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=3)),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
        migrations.DeleteModel(
            name='Anuncio',
        ),
    ]
