# Generated by Django 3.1.1 on 2020-09-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_anuncio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anuncios',
        ),
    ]
